apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: documentstream

labels:
  - pairs:
      app.kubernetes.io/managed-by: kustomize

resources:
  - namespace.yaml
  - configmap.yaml
  - gateway-deployment.yaml
  - gateway-service.yaml
  - servicemonitor.yaml
  - extract-deployment.yaml
  - classify-deployment.yaml
  - store-deployment.yaml
  - postgres-deployment.yaml
  - ingress.yaml
